[mongodb]
mongodb.devopsaws.store

[catalogue]
catalogue.devopsaws.store

[redis]
redis.devopsaws.store

[user]
user.devopsaws.store

[cart]
cart.devopsaws.store

[mysql]
mysql.devopsaws.store

[shipping]
shipping.devopsaws.store

[rabbitmq]
rabbitmq.devopsaws.store

[payment]
payment.devopsaws.store

[frontend]
frontend.devopsaws.store

[all:vars] # we can pass username and password from here for all the hosts in the inventory rather than giving them in command line
ansible_user=ec2-user
ansible_password=DevOps321