---

 - name: INSTALLING PYTHON
   include_role:
     name: common
     tasks_from: python_install

 - name: APPLICATION SETUP
   include_role:
    name: common
    tasks_from: appcode_install


 - name: SYSTEMD
   include_role:
    name: common
    tasks_from: systemd