---

    - name: INSTALLING NODEJS 
      include_role:
       name: common
       tasks_from: nodejs_install
    

    - name: APPLICATION SETUP
      include_role:
        name: common
        tasks_from: appcode_install

    
    - name: Download The Dependencies
      npm:
       path: /app
   
    - name: Copy Mongodb Repo
      copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDb Client
      package:
        name: mongodb-mongosh
        state: present
      
    - name: Check Products Loaded or Not
      command: mongosh --host mongodb.devopsaws.store --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: Print Catalogue Ouput 
      debug:
        msg: "{{ catalogue_output }}" 

    - name: Load Products 
      shell: mongosh --host mongodb.devopsaws.store < /app/db/master-data.js
      when: catalogue_output.stdout | int < 0
      
    - name: SYSTEMD 
      include_role:
       name: common
       tasks_from: systemd 


       
       

