- name: Copy catalogue service to system directory
  template:  #here it will change from copy to template as we gave code in template fro catalogue service
    src: catalogue.service.j2 # here .j2 should be added
    dest: /etc/systemd/system/catalogue.service
  notify: Reload systemd

- name: Start & Enable Catalogue Service
  service:
      name: catalogue
      state: started
      enabled: yes