---

- name: Disabling Default Nodejs
  command: dnf module disable nodejs -y

- name: Enabling  Nodejs:20
  command: dnf module enable nodejs:20 -y

- name: Installing Nodejs
  package:
    name: nodejs
    state: present