---

- name: Copy "{{ component }}" service
  template:
    src: "{{ component }}.service.j2"
    dest: /etc/systemd/system/{{ component }}.service

- name: Daemon Reload
  systemd_service:
    daemon_reload: true

- name: Enabling And Starting "{{ component }}" service
  service:
      name:  "{{ component }}"
      state: restarted # EVEN APP IS NOT RUNNING WE CAN RESTART
      enabled: yes