---

- name: NODEJS Installation
  include_role:
    name: common
    tasks_from: nodejs_install


- name: APPLICATION SETUP
  include_role:
    name: common
    tasks_from: appcode_install


- name: Dependenices Installation
  npm:
    path: /app

- name: SYSTEMD
  include_role:
    name: common
    tasks_from: systemd